In [2]:
import numpy as np

In [4]:
width_phase_half = 5
n = 2

In [ ]:
array_x = np.tile(np.array(list(range(-width_phase_half,width_phase_half))), (n,1))
print(array_x)

[[-5 -4 -3 -2 -1  0  1  2  3  4 -5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4 -5 -4 -3 -2 -1  0  1  2  3  4]]


In [13]:
twolist_array = np.array([[1, 2, 3],
                     [4, 5, 6]])
print(twolist_array)
num_functions = 4

[[1 2 3]
 [4 5 6]]


In [16]:
# twolist_array を n 回複製して、新たな配列を作成
# まず、twolist_array に次元を追加 (1, 2, 3)
twolist_expanded = twolist_array[np.newaxis, :, :]

# tile で n 回繰り返す
n =5
result_array = np.tile(twolist_expanded, (n, 1, 1))
print(result_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
phase_full = [twolist_array for _ in range(num_functions)]  # 4つの元の配列を作成
print(phase_full)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [4, 5, 6]])]
